on:
  push:
    branches:
      - master
  pull_request:
name: CI
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
          key: ${{ runner.os }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV
      - name: Install Packages
        run: hermit install -d
      - name: Test
        run: go test -v ./...
